version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - VictorAvelar
  ignore:
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.73
    - 0.12.83
